server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_bytes: 104857600
  max_block_duration: 5m

compactor:
  compaction:
    compacted_block_retention: 48h

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

query_frontend:
  max_outstanding_per_tenant: 2000
